packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@shopify/react-native-skia'
  - esbuild
  - react-native-libsodium
patchedDependencies:
  expo-image-picker@57.0.18: patches/expo-image-picker@57.0.18.patch
